version: "3.9"
services:
    scraper:
        build: scraper/.
        volumes:
            - ./scraper/src:/src
    web:
        build: web/.
        ports:
            - "5000:5000"
        volumes:
            - ./web/src:/src
        environment:
            FLASK_ENV: development
    mongo:
        image: "mongo"
        volumes:
            - ./mongo/database_snapshot:/database_snapshot
    redis:
        image: "redis:alpine"