version: "3.9"
services:
    http:
        build: http/.
        volumes:
            - ./mongo:/mongo
    mongo:
        image: "mongo"
        volumes:
            - mongodata:/data/db
            - ./mongo:/archives
volumes:
    mongodata: