version: "3.9"
services:
    http:
        build: http/.
    mongo:
        image: "mongo"
        ports:
            - "27017:27017"
        volumes:
            - mongodata:/data/db
            - ./mongo:/archives
volumes:
    mongodata: