version: "3.9"
services:
    scraper:
        build: scraper/.
        volumes:
            - ./scraper/src:/src
            - ./mongo:/mongo
    web:
        build: web/.
        ports:
            - "5000:5000"
        volumes:
            - ./web/src:/src
        environment:
            FLASK_ENV: development
    mongo:
        image: "mongo"
        volumes:
            - mongodata:/data/db
            - ./mongo:/archives
    redis:
        image: "redis:alpine"
volumes:
    mongodata: